export enum Role {
  BUYER = "BUYER",
  SELLER = "SELLER",
  SUPER_ADMIN = "SUPER_ADMIN",
  GOVERNMENT_OFFICER = "GOVERNMENT_OFFICER",
  MARKETPLACE_MANAGER = "MARKETPLACE_MANAGER",
  DISTRICT_COORDINATOR = "DISTRICT_COORDINATOR"
}
